name: eBUSd
version: "0.81-more-options.2"
slug: ebusd
description: >
  This Add-on runs eBUSd, a daemon for handling communication with eBUS devices
  connected to a 2-wire bus system (“energy bus” used by numerous heating systems)
  You currently need an eBUS hardware interface connected via usb to make use of this addon
url: https://community.home-assistant.io/t/an-ebusd-add-on/344852
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: "system"
boot: "auto"
uart: true
options:
  scanconfig: true
  foreground: true
  
  
schema:
  device: "device(subsystem=tty)"
  port: "port?"
  latency: "int(0,10000)?"
  readonly: "bool?"
  foreground: "bool?"
  scanconfig: "bool?"
  configpath: "str?"
  pollinterval: "int(0,30)?"
  accesslevel: "str?"
  httpport: "port?"
  logareas: "list(main|network|bus|update|all)?"
  loglevel: "list(error|notice|info|debug)?"
  mqtthost: "str?"
  mqttport: "int?"
  mqttuser: "str?"
  mqttpass: "str?"
  mqttjson: "bool?"
  mqttlog: "bool?"
  mqttretain: "bool?"
  mqtttopic: "str?"
  mqttverbose: "bool?"
  
ports:
  4711/tcp: 4711
  
map: 
  - config
